index/urls.py
from django.urls import path
from . import views
from .views import MyView, login_view, logout_view
urlpatterns = [
    path('', views.index, name="index"),
    path('university/', views.catalog, name="catalog"),
    path('university/<int:university_id>/', views.university, name="university"),
    path('client_form/', views.client_form, name="client_form"),
    path('myview/', MyView.as_view(), name='myview'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('delete-form/<int:form_id>/', views.delete_form, name="delete-form"),
]

turkish/urls.py
from django.contrib import admin
from django.urls import path, include
from turkish import settings



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('index.urls')),
]


if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls))
    ] + urlpatterns

index/models.py
from django.contrib.auth.models import User
from phonenumber_field.modelfields import PhoneNumberField
from django.db import models




class Client_forms(models.Model):
    name = models.CharField(max_length=30)
    number = PhoneNumberField(unique=True)
    country = models.CharField(max_length=50)
    language = models.CharField(max_length=20)
    school_class = models.CharField(max_length=50)
    date = models.DateField(auto_now_add=True, null=True, blank=True)


    class Meta:
        ordering = ['-date']

    def __str__(self):
        return self.name



class University(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    structure = models.TextField(null=True, blank=True)
    rating = models.TextField(null=True, blank=True)
    country = models.CharField(max_length=100)
    price = models.IntegerField()
    program = models.CharField(max_length=200)
    city = models.CharField(max_length=200, default=" ")


    def __str__(self):
        return self.title


class Faculty(models.Model):
    faculty = models.CharField(max_length=200)
    university = models.ForeignKey(University, null=True, blank=True, on_delete=models.CASCADE)

    def __str__(self):
        return self.faculty


class Image_src(models.Model):
    university = models.ForeignKey(University, on_delete=models.CASCADE, null=True)
    image_scr = models.TextField(default='images/1_first.png')
    first = models.BooleanField(default=True)
    second = models.BooleanField(default=True)


class MyModel(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE)




''

index/views.py
import re
from django.views.decorators.csrf import csrf_exempt
from django.contrib import messages
from django.shortcuts import render, redirect
from django.http import HttpResponse, Http404
from django.shortcuts import render
from django.db.models import Q
from wtforms import ValidationError
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import AuthenticationForm
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views.generic import TemplateView
from .models import *
from .form import MyFilterForm, ClientForm, OwnerLoginForm
from django.forms import ValidationError


class MyView(TemplateView):
    template_name = 'myapp/for_moderator.html'

    @login_required(login_url='index:login')
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)


def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(username=username, password=password)
            if user is not None:
                client = Client_forms.objects.all()
                login(request, user)
                return render(request, 'index/for_moderator.html', {'client': client})
    else:
        form = AuthenticationForm()
    return render(request, 'index/login.html', {'form': form})


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('index:login'))



def index(request):
    universities = University.objects.all()
    china_universities = universities.filter(country='Китай')
    turkey_universities = universities.filter(country='Турция')
    images = Image_src.objects.all()
    context = {'universities': universities, 'images': images, 'china_universities': china_universities, 'turkey_universities': turkey_universities}
    return render(request, 'index/index.html', context)


def catalog(request):
    form = MyFilterForm(request.GET)
    query = request.GET.get('query')
    universities = University.objects.all()
    images = Image_src.objects.all()
    if query:
        universities = universities.filter(Q(title__icontains=query) | Q(description__icontains=query) | Q(country__icontains=query) | Q(city__icontains=query))
    if form.is_valid():
        country = form.cleaned_data['country']
        price = form.cleaned_data['price']
        program = form.cleaned_data['program']
        if country != 'Все' and country:
            universities = universities.filter(country=country)
        if program != 'Все' and program:
            universities = universities.filter(program=program)
        if price != 'Все' and price:
            universities = universities.filter(price=price)
    context = {'universities': universities, 'images': images, 'query': query, 'form': form}
    return render(request, 'index/catalog.html', context)


def university(request, university_id):
    images = Image_src.objects.all()
    current_university = University.objects.get(pk=university_id)
    if current_university is not None:
        return render(request, 'index/university.html', {'current_university': current_university, 'images': images})
    else:
        raise Http404('Университет не найден.')


def search(request):
    query = request.GET.get('q')
    if query:
        results = University.objects.filter(Q(title__icontains=query) | Q(description__icontains=query) | Q(country__icontains=query) | Q(city__icontains=query) | Q(faculty__icontains=query))
    else:
        results = University.objects.none()
    context = {'results': results, 'query': query}
    return render(request, 'catalog.html', context)





@csrf_exempt
def client_form(request):
    if request.method == "POST":
        form = ClientForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Ваша форма была успешно отправлена.')
            return redirect('client_form')
        else:
            messages.error(request, 'Пожалуйста, заполните номер телефона корректно')
    else:
        form = ClientForm(request.GET)
    context = {'form': form}
    return render(request, 'index/client_form.html', context)


def delete_form(request, form_id):
    form = Client_forms.objects.get(pk=form_id)
    if request.method == "POST":
        form.delete()
        client = Client_forms.objects.all()
        return render(request, 'index/for_moderator.html', {'client': client})
    print('alo2')
    return render(request, 'index/for_moderator.html')

index/templates/index/catalog.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <meta charset="UTF-8">
    <title>Каталог университетов</title>
    <link rel="stylesheet" href="{% static 'css/style_1.css' %}">
    <script src="https://kit.fontawesome.com/8764cec082.js" crossorigin="anonymous"></script>
<!--    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"-->
<!--          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">-->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <style>
        a{
            color: white;
        }
    </style>
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>

<!--НАЧАЛО НАВБАРА-->

<div class="row full">
    <div class="col-md-4 col-12 element left">
        <i class="fa-solid fa-phone-volume"></i> <i class="fa-brands fa-instagram"></i> <i class="fa-brands fa-whatsapp"></i>
    </div>
    <div class="col-md-4 col-12 element">
        <img class="img-turk" src="https://static.tildacdn.com/tild3665-6535-4962-a362-353561373864/Group_1.png">
    </div>
    <div class="col-md-4 col-12 right element">
        +7 700 500 8920<br>
        office@turkdunyasi.kz
    </div>
</div>
<div class="row full_bottom">
    <div class="col-md-4 col-sm-12 element-bottom"></div>
    <div class="col-md-4 col-sm-12 element-bottom">
        <div class="row">
            <div class="col-md-4 col-sm-12 consult">
                <a href="{% url 'index' %}">Назад</a>
            </div>
            <div class="col-md-4 col-sm-12 consult">
                <a href="{% url 'client_form' %}">Консультация</a>
            </div>
            <div class="col-md-4 col-sm-12 consult">
                <a href="{% url 'index' %}">Подробнее</a>
            </div>
        </div>
    </div>
    <div class="col-md-4 col-sm-12 element-bottom"></div>
</div>

<!--КОНЕЦ НАВБАРА-->

<!--НАЧАЛО ФИЛЬТР-->
<div class="row filter-and-search">
    <div class="col-md-6 filter">
        <div class="dropdown">
            <button class="btn btn-primary dropdown-toggle d-sm-block" type="button" data-toggle="dropdown">
                Фильтр <span class="caret"></span>
            </button>
            <div class="dropdown-menu">
                    <form method="get" class="form-inline" action="">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-primary">Filter</button>
                    </form>
            </div>
        </div>
    </div>
<!--КОНЕЦ ФИЛЬТР-->
<!--НАЧАЛО ПОИСКА-->
    <div class="col-md-3 search">
        <div class="search1">
            <form class="form-inline" action="" method="get">
                <input  placeholder="Университет" class="form-control mr-sm-2" type="text" name="query" aria-label="search">
                <button class="btn btn-outline-primary my-2 my-sm-0" type="submit">Поиск</button>
            </form>
        </div>
    </div>
</div>
<!--КОНЕЦ ПОИСКА-->
<!--НАЧАЛО КАТАЛОГА-->
<div class="row universities-container">
    {% if query%}
      {% if universities %}
        {% for result in universities %}
          <div class="col-md-4 col-12 university">
            <div class="change-photos">
                {% for image in images %}
                    {% if image.university.id == result.id and image.first %}
                        <div class="change-photo">
                            <a href="{% url 'university' result.pk %}">
                                <img src="{{image.image_scr}}" alt="">
                            </a>
                        </div>
                    {% endif %}
                    {% if image.university.id == result.id and image.second %}
                        <div class="change-photo">
                            <a href="{% url 'university' result.pk %}">
                                <img src="{{image.image_scr}}" alt="">
                            </a>
                        </div>
                    {% endif %}
                {% endfor %}

            </div>
            <h2 class="university_text_basic">{{ result.title }}</h2>
            <p class="university_text"><b>город {{ result.city }}</b></p>
            <p class="university_text"><b>{{ result.price }}$</b></p>
          </div>
        {% endfor %}
      {% else %}
            <div class="col-md-12 col-12 nothing">
                <h5>Ничего не найдено</h5>
            </div>
      {% endif %}
    {% else %}
        {% if universities %}
            {% for university in universities %}
                <div class="col-md-4 col-12 university">
                    <div class="change-photos">
                        {% for image in university.image_src_set.all %}
                            {% if image.first %}
                                <div class="change-photo">
                                    <a href="{% url 'university' university.pk %}">
                                        <img src="{{image.image_scr}}" alt="">
                                    </a>
                                </div>
                            {% endif %}
                            {% if image.second %}
                                <div class="change-photo">
                                    <a href="{% url 'university' university.id %}">
                                        <img src="{{image.image_scr}}" alt="">
                                    </a>
                                </div>
                            {% endif %}
                        {% endfor %}
                    </div>
                    <h2 class="university_text_basic">{{ university.title }}</h2>
                    <p class="university_text"><b>город {{ university.city }}</b></p>
                    <p class="university_text"><b>{{ university.price }}$</b></p>
                </div>
            {% endfor %}
        {% else %}
            <div class="col-md-12 col-12 nothing">
                <h5>Ничего не найдено</h5>
            </div>
        {% endif %}
    {% endif %}
</div>

<!--КОНЕЦ КАТАЛОГА-->

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
</body>
</html>

index/templates/index/client_form.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <meta charset="UTF-8">
    <title>Форма для клиента</title>
    <link rel="stylesheet" href="{% static 'css/style_2.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script>
    !function (w, d, t) {
      w.TiktokAnalyticsObject=t;var ttq=w[t]=w[t]||[];ttq.methods=["page","track","identify","instances","debug","on","off","once","ready","alias","group","enableCookie","disableCookie"],ttq.setAndDefer=function(t,e){t[e]=function(){t.push([e].concat(Array.prototype.slice.call(arguments,0)))}};for(var i=0;i<ttq.methods.length;i++)ttq.setAndDefer(ttq,ttq.methods[i]);ttq.instance=function(t){for(var e=ttq._i[t]||[],n=0;n<ttq.methods.length;n++)ttq.setAndDefer(e,ttq.methods[n]);return e},ttq.load=function(e,n){var i="https://analytics.tiktok.com/i18n/pixel/events.js";ttq._i=ttq._i||{},ttq._i[e]=[],ttq._i[e]._u=i,ttq._t=ttq._t||{},ttq._t[e]=+new Date,ttq._o=ttq._o||{},ttq._o[e]=n||{};var o=document.createElement("script");o.type="text/javascript",o.async=!0,o.src=i+"?sdkid="+e+"&lib="+t;var a=document.getElementsByTagName("script")[0];a.parentNode.insertBefore(o,a)};

      ttq.load('CGNV2OJC77UET5SJLL1G');
      ttq.page();
    }(window, document, 'ttq');
    </script>

    <!-- Google Tag Manager -->
    <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
    new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
    j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
    'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
    })(window,document,'script','dataLayer','GTM-NK6ZSVL');
    </script>
    <!-- End Google Tag Manager -->
    <!-- Google tag (gtag.js) -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-54Z1GS962X">
    </script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'G-54Z1GS962X');
    </script>

</head>
<body class="formbody">
<div class="formtext">
    <h2><b>Пожалуйста заполните форму</b></h2>
</div>
<div class="row">
    <div class="col-md-6 col-12 formimagediv">
        <img class="formimage"
             src="https://thumb.tildacdn.com/tild6332-6535-4261-a561-376666636634/-/format/webp/noroot.png">
    </div>
    <div class="col-md-6 col-12 formdiv">
        <form class="client-form" method="POST" action="{% url 'client_form' %}">
            {{ form.as_table }}
            <input type="submit" value="Отправить">
        </form>
        <div class="messages">
            {% if messages %}
            {% for message in messages %}
            <h3 class="messages">{{ message }}</h3>
            {% endfor %}
            {% endif %}
        </div>
    </div>

</div>

</body>
</html>

index/templates/index/university.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <title>University</title>
    <link rel="stylesheet" href="{% static 'css/style_1.css' %}">
    <script src="https://kit.fontawesome.com/8764cec082.js" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
</head>
<body>
<!--    НАЧАЛО КАРУСЕЛЬ И ДИСКРИПШЕН-->
<div class="exit">
    <a href="{% url 'client_form' %}"><button type="button" class="btn btn-link nav-btn" onclick="{% url 'client_form' %}">Консультация</button></a>
    <a href="{% url 'catalog' %}" class="close"></a>
</div>
<div class="row photos-and-desc">
    <div class="col-md-2 col-sm-1">
    </div>
    <div class="col-md-4 col-sm-10 photos">
        <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
                <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
            </ol>
            <div class="carousel-inner">
                {% for img in current_university.image_src_set.all %}
                {% if img.first %}
                <div class="carousel-item active">
                    <img class="d-block w-100" src="{{img.image_scr}}" alt="First slide">
                </div>
                {% endif %}
                {% if img.second %}
                <div class="carousel-item">
                    <img class="d-block w-100" src="{{img.image_scr}}" alt="Second slide">
                </div>
                {% endif %}
                {% if img.first is False and img.second is False %}
                <div class="carousel-item">
                    <img class="d-block w-100" src="{{img.image_scr}}" alt="Third slide">
                </div>
                {% endif %}
                {% endfor %}
            </div>
            <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
    </div>

    <div class="col-md-4 col-sm-10 des">
        <div class="texts">
            <a class="title_desc">{{current_university.title}}</a><br>
        </div>
        <div class="texts price">
            <a class="price_desc">{{current_university.price}}$</a><br>
        </div>
        <div class="texts">
            <a class="desc_desc">{{current_university.description}}</a><br>
        </div>
        {% if current_university.structure is not None %}
        <div class="texts">
            <a class="conception_desc">Состав университета</a><br>
            <a class="conception_desc">{{current_university.structure}}</a>
        </div>
        {% endif %}
        {% if current_university.rating %}
        <div class="texts">
            <a class="rating_desc">Рейтинг университета</a><br>
            <a class="rating_desc">{{current_university.structure}}</a>
        </div>
        {% endif %}
        <div class="texts">
            {% if current_university.country == 'Турция' %}
            <a class="language_desc">Язык обучения: Английский и Турецкий</a><br>
            {% else %}
            <a class="language_desc">Язык обучения: Английский и Китайский</a><br>
            {% endif %}
        </div>
        <div class="texts">
            {% if current_university.id == 6 %}
            <a class="program_desc">Программа: Платная</a><br>
            {% elif current_university.country == 'Турция' and current_university.id != 6 %}
            <a class="program_desc">Программа: Квота для иностранца</a><br>
            {% else %}
            <a class="program_desc">Программа: Правительственный грант</a><br>
            {% endif %}
        </div>
        <div class="texts">
            <a class="country_desc">Страна: {{current_university.country}}</a><br>
        </div>

    </div>
    <div class="col-md-2 col-sm-1">
    </div>
</div>
<!--    КОНЕЦ КАРУСЕЛЬ И ДИСКРИПШЕН-->

<div class="other">
    <style>
      .btn-link-gray {
        text-decoration: underline;
        color: gray;
      }

      .btn-link-black {
        text-decoration: underline;
        color: black;
      }

      .btn-link-gray:hover,
      .btn-link-gray:focus {
        color: gray;
      }

      .btn-link-black:hover,
      .btn-link-black:focus {
        color: black;
      }

      .btn-link-gray:visited {
        color: gray;
      }



    </style>

    <div class="container contliv">
        <div class="row bus">
            <div class="col-md-4 col-sm-4">
                <a class="btn btn-link btn-link-dark text-dark living" id="button1" href="#" data-toggle="collapse"
                   data-target="#info1" aria-expanded="false" aria-controls="info1" onclick="collapseOthers(this)">
                    <b>Проживание</b>
                </a>
            </div>
            <div class="col-md-4 col-sm-4">
                <a class="btn btn-link btn-link-dark text-dark requir" id="button2" href="#" data-toggle="collapse"
                   data-target="#info2" aria-expanded="false" aria-controls="info2" onclick="collapseOthers(this)">
                    <b>Требования</b>
                </a>
            </div>
            <div class="col-md-4 col-sm-4">
                <a class="btn btn-link btn-link-dark text-dark special" id="button3" href="#" data-toggle="collapse"
                   data-target="#info3" aria-expanded="false" aria-controls="info3" onclick="collapseOthers(this)">
                    <b>Специальности</b>
                </a>
            </div>
        </div>
        {% if current_university.country == 'Турция' %}
        <div id="content1" class="content"><i>Университет не предлагает обжежитье для иностранных студентов, жилье со
            стороны ВУЗа выдается только для граждан Турции.<br>
            Найти жилье, заселиться и оформить необходимые документы помогает компания.</i>
        </div>
        {% else %}
        <div id="content1" class="content"><i>Университет предоставляет бесплатное проживание на весь период обучения.</i>
        </div>
        {% endif %}

        {% if current_university.id == 5 or current_university.id == 6 %}
        <div id="content2" class="content"><i>Абитуриент - официальные школьные аттестаты и транскрипты.</i> <br>
            <i>Средняя успеваемость (допускается до трех троек. *каждый абитуриент рассматривается индивидуально)</i><br>
            <p></p><br>
            <b>Перечень документов:</b>
            <ul>
                <li>ФИО (по документу)</li>
                <li>Год рождения</li>
                <li>ФИО родителей</li>
                <li>Тел.номер студента</li>
                <li>Тел.номер родителей</li>
                <li>Эл.почта</li>
                <li>Адрес проживания</li>
                <li>Семья (полная/в разводе/смерть одного из родителей/гражданский брак)</li>
            </ul>
            <b>Список необходимых документов:</b>
            <ul>
                <li>Загран.паспорт</li>
                <li>Год рождения</li>
                <li>Табель 10 кл</li>
                <li>Аттестат 9 кл</li>
                <li>Аттестат 11 кл (если есть)</li>
                <li>Эл.почта</li>
                <li>Фото 3*4 (4 шт)</li>
                <li>Фото 5*6 (4 шт)</li>
            </ul>
        </div>
        {% elif current_university.country == 'Турция' or current_university.id == 8 %}
        <div id="content2" class="content">
            <b><i>Документы, необходимые для загрузки в систему для зачисления:</i></b><br>
            <b>1. Оригинал документа</b> об окончании диплома или аттестата школы за 11 класс.<br>
            Необходимо загрузить в нашу систему оригинал аттестата/диплома в формате PDF.<br>
            <b>2. Перевод диплома/аттестата:</b><br>
            Необходимо, чтобы турецкий или английский перевод аттестата/диплома был загружен в систему в формате
            PDF, одобренном официальными органами (консульством Турции, нотариусом, присяжным переводчиком).<br>
            <b>3. Транскрипт:</b><br>
            Необходимо, чтобы оригинал заверенной копии транскрипта, полученной в средней школе/колледжа, был
            загружен в систему в формате PDF, а также оригинальная копия перевода на турецкий или английский язык,
            утвержденная официальными органами (консульство Турции, нотариус, аккредитованный переводчик).<br>
            <b>4. Паспорт:</b><br>
            Необходимо, чтобы отсканированная версия паспорта или страница документа, удостоверяющего личность
            временной защиты, содержащая идентификационную информацию с фотографией (первая страница), была
            загружена в систему в формате PDF.<br>
            <b>5. Фотография:</b><br>
            Кандидат должен добавить цифровую копию своей фотографии. Эта фотография должна быть официального и
            паспортного формата (4,5 см x 6 см), сделана с открытым лицом и должна быть сделана в течение последних
            6 (шести) месяцев, при этом кандидат должен быть четко узнаваем на фотографии. Просим не использовать
            бледные, темные фотографии, сделанные с большого расстояния, с любыми аксессуарами, такими как
            солнцезащитные очки и т. д.<br>
            <b>6. Формат документов:</b><br>
            Вы должны загрузить документы в формате PDF, файлы должны быть объединены в 1 файл, потому что можно
            загрузить только 1 файл. Размер файла должен быть менее 5 МБ, а расширение файла должен быть в формате
            PDF.<br>
            <b>Требования, которые необходимо учитывать:</b><br>
            • Необходим адрес электронной почты кандидата. Поскольку с кандидатом будут связываться через этот адрес
            электронной почты на каждом этапе, рекомендуется постоянная почта кандидата в процессах подачи заявок,
            размещения и регистрации, важно, чтобы кандидаты не сообщали никому свои адреса электронной почты и
            пароли в целях их собственной безопасности.<br>
            • Процесс подачи заявки индивидуален, и каждый кандидат заполнит необходимую информацию в приложении и
            загрузит документы в нашу систему.<br>
            • Заявка, аттестат/диплом и их приложения, и другие документы, загруженные в нашу систему, просим их
            проверить на корректность, если не правильно загрузить документы и/или указываемые личные данные
            диплома/аттестата были сфальсифицированы, то процесс зачисления кандидата аннулируется, и апелляции не
            подлежит.
        </div>
        {% else %}
        <div id="content2" class="content">
            <i>Абитуриент - официальные школьные аттестаты и транскрипты.<br>
            Средняя успеваемость (допускается до трех троек. *каждый абитуриент рассматривается индивидуально)</i><br>
            <p></p><br>
            <b>Перечень документов:</b>
            <ul>
                <li>Фото 3*4</li>
                <li>Паспорт</li>
                <li>Табель/транскрипт текущего учебного года - перевести и нотариально заверить</li>
                <li>2 рекомендационных письма - если на русском перевести и нотарильно заверить мотивационное письмо
                    - на английском справка о несудимости - перевести на англ и нотарильно заверить</li>
                <li>медицинский бланк</li>
            </ul>
        </div>
        {% endif %}

        <div id="content3" class="content">
            <ul>
                {% for fac in current_university.faculty_set.all %}
                <li>{{fac}}</li>
                {% endfor %}
            </ul>
        </div>


    </div>


</div>
<script src="{% static 'js/script.js' %}"></script>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
</body>
</html>